# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test02ConfigSEILocalizadores():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["local_do_teste"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_0101LocalizadoresLugares(self):
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI")
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Localizadores\"]").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Lugares\"]").click()
    self.driver.find_element(By.XPATH, "//*[contains(@link,\'lugar_localizador_listar\')]").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Lugar 01")
    self.driver.find_element(By.NAME, "sbmCadastrarLugarLocalizador").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Lugar 02")
    self.driver.find_element(By.NAME, "sbmCadastrarLugarLocalizador").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Localizadores\"]").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Localizadores\"]/../../ul/li[contains(.,\'Tipos\')]/a").click()
    self.driver.find_element(By.XPATH, "//*[contains(@link,\'tipo_localizador_listar\')]").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    self.driver.find_element(By.ID, "txtSigla").send_keys("TLOC01")
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Tipo de Localizador 01")
    self.driver.find_element(By.ID, "txaDescricao").send_keys("desc1")
    self.driver.find_element(By.NAME, "sbmCadastrarTipoLocalizador").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    self.driver.find_element(By.ID, "txtSigla").send_keys("TLOC02")
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Tipo de Localizador 02")
    self.driver.find_element(By.ID, "txaDescricao").click()
    self.driver.find_element(By.ID, "txaDescricao").send_keys("desc2")
    self.driver.find_element(By.NAME, "sbmCadastrarTipoLocalizador").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Localizadores\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Listar").click()
    self.driver.find_element(By.CSS_SELECTOR, "#btnNovo > .infraTeclaAtalho").click()
    dropdown = self.driver.find_element(By.ID, "selTipoLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Tipo de Localizador 01']").click()
    self.driver.find_element(By.ID, "selTipoLocalizador").click()
    self.driver.find_element(By.ID, "txtComplemento").click()
    self.driver.find_element(By.ID, "txtComplemento").send_keys("complemento localizador 01")
    dropdown = self.driver.find_element(By.ID, "selTipoSuporte")
    dropdown.find_element(By.XPATH, "//option[. = 'Papel']").click()
    self.driver.find_element(By.ID, "selTipoSuporte").click()
    dropdown = self.driver.find_element(By.ID, "selLugarLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Lugar 01']").click()
    self.driver.find_element(By.ID, "selLugarLocalizador").click()
    dropdown = self.driver.find_element(By.ID, "selStaEstado")
    dropdown.find_element(By.XPATH, "//option[. = 'Aberto']").click()
    self.driver.find_element(By.ID, "selStaEstado").click()
    self.driver.find_element(By.NAME, "sbmCadastrarLocalizador").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Localizadores\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Listar").click()
    self.driver.find_element(By.CSS_SELECTOR, "#btnNovo > .infraTeclaAtalho").click()
    dropdown = self.driver.find_element(By.ID, "selTipoLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Tipo de Localizador 02']").click()
    self.driver.find_element(By.ID, "selTipoLocalizador").click()
    dropdown = self.driver.find_element(By.ID, "selTipoSuporte")
    dropdown.find_element(By.XPATH, "//option[. = 'Papel']").click()
    self.driver.find_element(By.ID, "selTipoSuporte").click()
    self.driver.find_element(By.ID, "selTipoSuporte").click()
    dropdown = self.driver.find_element(By.ID, "selLugarLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Lugar 02']").click()
    self.driver.find_element(By.ID, "selLugarLocalizador").click()
    dropdown = self.driver.find_element(By.ID, "selStaEstado")
    dropdown.find_element(By.XPATH, "//option[. = 'Aberto']").click()
    self.driver.find_element(By.ID, "selStaEstado").click()
    self.driver.find_element(By.NAME, "sbmCadastrarLocalizador").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Localizadores\"]").click()
  
