# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test02ConfigSEILocalizadores():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_0101LocalizadoresLugares(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[21]/a")))
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[21]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[21]/ul/li[4]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[21]/ul/li[4]/ul/li[2]/a").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Lugar 01")
    self.driver.find_element(By.CSS_SELECTOR, ".infraButton:nth-child(1) > .infraTeclaAtalho").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Lugar 02")
    self.driver.find_element(By.NAME, "sbmCadastrarLugarLocalizador").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[21]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[21]/ul/li[3]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[21]/ul/li[3]/ul/li[2]/a").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    self.driver.find_element(By.ID, "txtSigla").send_keys("TLOC01")
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Tipo de Localizador 01")
    self.driver.find_element(By.ID, "txaDescricao").send_keys("desc1")
    self.driver.find_element(By.CSS_SELECTOR, ".infraButton:nth-child(1) > .infraTeclaAtalho").click()
    self.driver.find_element(By.ID, "btnNovo").click()
    self.driver.find_element(By.ID, "txtSigla").send_keys("TLOC02")
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Tipo de Localizador 02")
    self.driver.find_element(By.ID, "txaDescricao").click()
    self.driver.find_element(By.ID, "txaDescricao").send_keys("desc2")
    self.driver.find_element(By.NAME, "sbmCadastrarTipoLocalizador").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[21]/a").click()
    self.driver.find_element(By.LINK_TEXT, "Listar").click()
    self.driver.find_element(By.CSS_SELECTOR, "#btnNovo > .infraTeclaAtalho").click()
    dropdown = self.driver.find_element(By.ID, "selTipoLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Tipo de Localizador 01']").click()
    self.driver.find_element(By.ID, "selTipoLocalizador").click()
    self.driver.find_element(By.ID, "txtComplemento").click()
    self.driver.find_element(By.ID, "txtComplemento").send_keys("complemento localizador 01")
    dropdown = self.driver.find_element(By.ID, "selTipoSuporte")
    dropdown.find_element(By.XPATH, "//option[. = 'Papel']").click()
    self.driver.find_element(By.ID, "selTipoSuporte").click()
    dropdown = self.driver.find_element(By.ID, "selLugarLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Lugar 01']").click()
    self.driver.find_element(By.ID, "selLugarLocalizador").click()
    dropdown = self.driver.find_element(By.ID, "selStaEstado")
    dropdown.find_element(By.XPATH, "//option[. = 'Aberto']").click()
    self.driver.find_element(By.ID, "selStaEstado").click()
    self.driver.find_element(By.NAME, "sbmCadastrarLocalizador").click()
    self.driver.find_element(By.CSS_SELECTOR, "#lnkSairSistema > .infraImg").click()
    self.driver.close()
  
