# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test06SEIGDListasEliminacaoGestao():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["SELENIUMTEST_MODALIDADE"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor=os.environ["SELENIUMTEST_SELENIUMHOST_URL"], desired_capabilities=DesiredCapabilities.CHROME)

    if ((not 'maximizar_screen' in os.environ) or os.environ['maximizar_screen'] == 'true'):
        self.driver.maximize_window()

    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_0610GerarListagem(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    #self.driver.find_element(By.XPATH, "//span[contains(text(),'Gestão Documental')]/..").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]/..").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "chkInfraItem0")))
    self.driver.find_element(By.XPATH, "//input[@id='chkInfraItem0']/..").click()
    self.driver.find_element(By.ID, "btnGerarListagem").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnGerarListagem").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]/../../../../a").click()
    #self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Gestão das Listagens")))
    self.driver.find_element(By.LINK_TEXT, "Gestão das Listagens").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos de Eliminação (2 registros):"
    #self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[3]/td[3]").click()
    elements = self.driver.find_elements(By.XPATH, "//td[starts-with(.,\'99994.000001\')]")
    assert len(elements) > 0
    #self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[3]").click()
    elements = self.driver.find_elements(By.XPATH, "//td[starts-with(.,\'99994.000002\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[9]/a[1]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (4 registros):"
    self.driver.find_element(By.XPATH, "//a[@id='lnkSairSistema']").click()
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]/..").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão das Listagens").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[3]/td[9]/a[1]/img")))
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[3]/td[9]/a[1]/img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (1 registro):"
    self.driver.find_element(By.ID, "btnCancelar").click()
  
  def test_0620AlterarListagem(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão das Listagens").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[9]/a/img[contains(@title,'Editar Listagem de Eliminação')]").click()
    self.driver.switch_to.alert.accept()
    time.sleep(10)
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[9]/a/img[contains(@title,'Remover Processos')]").click()
    self.driver.find_element(By.XPATH, "//input[@id='chkInfraItem0']/..").click()
    self.driver.find_element(By.XPATH, "//*[@id='btnExcluirListagem']").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (3 registros):"
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.XPATH, "//*[@id='btnExcluirListagem']").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.ID, "divInfraAreaTelaD").click()
    self.driver.find_element(By.ID, "frmPrepararListagemEliminacao").click()
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
    self.driver.find_element(By.XPATH, "//*[@id=\"btnFechar\"]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[9]/a/img[contains(@title,'Adicionar Processos')]").click()
    self.driver.find_element(By.XPATH, "//input[@id='chkInfraItem0']/..").click()
    self.driver.find_element(By.ID, "btnAdicionarListagem").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (3 registros):"
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnAdicionarListagem").click()
    self.driver.find_element(By.ID, "btnFechar").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[9]/a/img[contains(@title,'Concluir edição da listagem')]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos de Eliminação (2 registros):"
  
