# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test0620SEIGDVerificarPrazos():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_0620VerificarPrazosUnidadeTeste(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selInfraUnidades")))
    dropdown = self.driver.find_element(By.ID, "selInfraUnidades")
    dropdown.find_element(By.XPATH, "//option[. = 'TESTE']").click()
    self.driver.find_element(By.ID, "selInfraUnidades").click()
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//td[contains(.,\'Prazo expirado!\')]")))
    assert self.driver.find_element(By.XPATH, "//td[contains(.,\'Prazo expirado!\')]").text == "Prazo expirado!"
    elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'1 ano, 9 meses\')]")
    assert len(elements) > 0
  
  def test_0630VerificarPrazosUnidadeArquivo(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//td[contains(.,\'0 ano\')]")))
    elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'0 anos, 9 meses\')]")
    assert len(elements) > 0
    assert self.driver.find_element(By.XPATH, "//td[contains(.,\'10 anos\')]").text == "10 anos"
  
