# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test0620SEIGDVerificarPrazos():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["local_do_teste"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_0620VerificarPrazosUnidadeTeste(self):
    # Test name: 06-20-VerificarPrazos-UnidadeTeste
    # Step # | name | target | value
    # 1 | open | /sip/login.php?sigla_orgao_sistema=ABC&sigla_sistema=SEI&infra_url=L3NlaS8= | 
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema=ABC&sigla_sistema=SEI&infra_url=L3NlaS8=")
    # 2 | type | id=txtUsuario | teste
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    # 3 | type | id=pwdSenha | teste
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    # 4 | click | id=Acessar | 
    self.driver.find_element(By.ID, "Acessar").click()
    # 5 | click | linkText=TESTE | 
    self.driver.find_element(By.LINK_TEXT, "TESTE").click()
    # 6 | waitForElementVisible | //*[@id="divInfraAreaTabela"]/table | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table")))
    # 7 | click | id=txtInfraSiglaUnidade | 
    self.driver.find_element(By.ID, "txtInfraSiglaUnidade").click()
    # 8 | type | id=txtInfraSiglaUnidade | TESTE
    self.driver.find_element(By.ID, "txtInfraSiglaUnidade").send_keys("TESTE")
    # 9 | click | id=sbmPesquisar | 
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    # 10 | waitForElementVisible | //*[@id="divInfraAreaTabela"]/table | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table")))
    # 11 | click | xpath=//tr[2]/td/div/label | 
    self.driver.find_element(By.XPATH, "//tr[2]/td/div/label").click()
    # 12 | click | linkText=TESTE | 
    self.driver.find_element(By.LINK_TEXT, "TESTE").click()
    # 13 | click | linkText=Arquivo da Unidade | 
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    # 14 | waitForElementVisible | //td[contains(.,'Prazo expirado!')] | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//td[contains(.,\'Prazo expirado!\')]")))
    # 15 | verifyText | //td[contains(.,'Prazo expirado!')] | Prazo expirado!
    assert self.driver.find_element(By.XPATH, "//td[contains(.,\'Prazo expirado!\')]").text == "Prazo expirado!"
    # 16 | verifyElementPresent | //td[contains(.,'1 ano, 9 meses')] | 
    elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'1 ano, 9 meses\')]")
    assert len(elements) > 0
  
  def test_0630VerificarPrazosUnidadeArquivo(self):
    # Test name: 06-30-VerificarPrazos-UnidadeArquivo
    # Step # | name | target | value
    # 1 | open | /sip/login.php?sigla_orgao_sistema=ABC&sigla_sistema=SEI&infra_url=L3NlaS8= | 
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema=ABC&sigla_sistema=SEI&infra_url=L3NlaS8=")
    # 2 | type | id=txtUsuario | arquivista01
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    # 3 | type | id=pwdSenha | arquivista01
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    # 4 | click | id=Acessar | 
    self.driver.find_element(By.ID, "Acessar").click()
    # 5 | click | linkText=Arquivo da Unidade | 
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    # 6 | waitForElementVisible | //td[contains(.,'0 ano')] | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//td[contains(.,\'0 ano\')]")))
    # 7 | verifyElementPresent | //td[contains(.,'0 anos, 9 meses')] | 
    elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'0 anos, 9 meses\')]")
    assert len(elements) > 0
    # 9 | verifyText | //td[contains(.,'10 anos')] | 10 anos
    assert self.driver.find_element(By.XPATH, "//td[contains(.,\'10 anos\')]").text == "10 anos"
  
