# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test08SEIGDListasRecolhimentoGestao():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_0810GerarListagem(self):
    self.driver.get("http://seigd.intra.planejamento//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[10]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[10]/ul/li[3]/a").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    self.driver.find_element(By.ID, "chkInfraItem0").click()
    self.driver.find_element(By.ID, "btnGerarListagem").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnGerarListagem").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[10]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[10]/ul/li[3]/a").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão das Listagens").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Listagens de Recolhimento (2 registros):"
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[3]/td[3]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[3]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[6]/a[1]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (4 registros):"
    self.driver.find_element(By.ID, "btnCancelar").click()
    self.driver.find_element(By.XPATH, "(//img[@title=\'Visualizar Listagem de Recolhimento\'])[2]").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (1 registro):"
    self.driver.find_element(By.ID, "btnCancelar").click()
  
  def test_0820AlterarListagem(self):
    self.driver.get("http://seigd.intra.planejamento//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[10]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[10]/ul/li[3]/a").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão das Listagens").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[6]/a[2]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[6]/a[3]").click()
    self.driver.find_element(By.ID, "chkInfraItem0").click()
    self.driver.find_element(By.ID, "btnExcluirListagem").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (3 registros):"
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnExcluirListagem").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.ID, "divInfraAreaTelaD").click()
    self.driver.find_element(By.ID, "frmPrepararListagemRecolhimento").click()
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
    self.driver.find_element(By.XPATH, "//*[@id=\"btnFechar\"]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[6]/a[2]").click()
    self.driver.find_element(By.ID, "chkInfraItem0").click()
    self.driver.find_element(By.ID, "btnAdicionarListagem").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (3 registros):"
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnAdicionarListagem").click()
    self.driver.find_element(By.ID, "btnFechar").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[6]/a[4]").click()
    self.driver.switch_to.alert.accept()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Listagens de Recolhimento (2 registros):"
  
