# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test0204SEIGDFloodProcsAcessoInfAut():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_cadastrarProcessosFlood(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "lblUsuario").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selInfraUnidades")))
    dropdown = self.driver.find_element(By.ID, "selInfraUnidades")
    dropdown.find_element(By.XPATH, "//option[. = 'TESTE']").click()
    self.driver.find_element(By.ID, "selInfraUnidades").click()
    for i in range(0, 5):
      WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Iniciar Processo")))
      self.driver.find_element(By.LINK_TEXT, "Iniciar Processo").click()
      self.vars["error"] = len(self.driver.find_elements(By.XPATH, "//a[contains(text(),\'Acesso à Informação: Demanda do e-SIC\')]"))
      if self.driver.execute_script("return (arguments[0]==0)", self.vars["error"]):
        self.driver.find_element(By.ID, "imgExibirTiposProcedimento").click()
      self.driver.find_element(By.LINK_TEXT, "Acesso à Informação: Demanda do e-SIC").click()
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "txtDescricao")))
      self.driver.find_element(By.ID, "txtDescricao").send_keys("teste arquivo")
      self.driver.find_element(By.ID, "optPublico").click()
      self.driver.find_element(By.CSS_SELECTOR, "#divInfraBarraComandosInferior > #btnSalvar > .infraTeclaAtalho").click()
      self.driver.switch_to.frame(1)
      WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".botaoSEI:nth-child(1) > .infraCorBarraSistema")))
      self.driver.find_element(By.CSS_SELECTOR, ".botaoSEI:nth-child(1) > .infraCorBarraSistema").click()
      WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Externo")))
      self.driver.find_element(By.LINK_TEXT, "Externo").click()
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "selSerie")))
      dropdown = self.driver.find_element(By.ID, "selSerie")
      dropdown.find_element(By.XPATH, "//option[. = 'Abaixo-Assinado']").click()
      time.sleep(1)
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "txtDataElaboracao")))
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "selSerie")))
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "txtDataElaboracao")))
      self.driver.find_element(By.ID, "txtDataElaboracao").click()
      self.driver.find_element(By.ID, "txtDataElaboracao").send_keys("01/01/2019")
      self.driver.find_element(By.ID, "optDigitalizado").click()
      dropdown = self.driver.find_element(By.ID, "selTipoConferencia")
      dropdown.find_element(By.XPATH, "//option[. = 'Cópia Autenticada Administrativamente']").click()
      self.driver.find_element(By.ID, "selTipoConferencia").click()
      self.driver.find_element(By.ID, "optPublico").click()
      self.driver.find_element(By.ID, "filArquivo").send_keys("teste.pdf")
      WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraTd:nth-child(2)")))
      self.driver.find_element(By.CSS_SELECTOR, ".infraTd:nth-child(2)").click()
      assert self.driver.find_element(By.CSS_SELECTOR, ".infraTd:nth-child(2) > div").text == "teste.pdf"
      self.driver.find_element(By.CSS_SELECTOR, "#divInfraBarraComandosInferior > #btnSalvar").click()
      WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Autenticar Documento\']")))
      self.vars["window_handles"] = self.driver.window_handles
      self.driver.find_element(By.XPATH, "//img[@alt=\'Autenticar Documento\']").click()
      self.vars["win9226"] = self.wait_for_window(2000)
      self.vars["root"] = self.driver.current_window_handle
      self.driver.switch_to.window(self.vars["win9226"])
      WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selCargoFuncao")))
      dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
      dropdown.find_element(By.XPATH, "//option[. = 'Gestor de Contrato']").click()
      self.driver.find_element(By.ID, "selCargoFuncao").click()
      time.sleep(2)
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "pwdSenha")))
      self.driver.find_element(By.ID, "pwdSenha").click()
      self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
      self.driver.find_element(By.ID, "btnAssinar").click()
      self.driver.switch_to.window(self.vars["root"])
      self.driver.find_element(By.ID, "lnkInfraMenuSistema").click()
    print(str("fim"))
    print(str("fim2"))
  
