# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test04SEIGDRunAgendamento():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["local_do_teste"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_runAgendamento(self):
    # Test name: RunAgendamento
    # Step # | name | target | value
    # 1 | open | /sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8= | 
    self.driver.get(os.environ["base_url"]+"//sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    # 2 | click | id=divUsuario | 
    self.driver.find_element(By.ID, "divUsuario").click()
    # 3 | click | id=txtUsuario | 
    self.driver.find_element(By.ID, "txtUsuario").click()
    # 4 | type | id=txtUsuario | teste
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    # 5 | click | id=pwdSenha | 
    self.driver.find_element(By.ID, "pwdSenha").click()
    # 6 | type | id=pwdSenha | teste
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    # 7 | click | id=Acessar | 
    self.driver.find_element(By.ID, "Acessar").click()
    # 8 | click | //a[contains(.,'Infra')] | 
    self.driver.find_element(By.XPATH, "//a[contains(.,\'Infra\')]").click()
    # 9 | click | linkText=Agendamentos | 
    self.driver.find_element(By.LINK_TEXT, "Agendamentos").click()
    # 11 | click | xpath=//div[@id='divInfraAreaTabela']/table/tbody/tr[contains(.,'MdGdAgendamentoRN :: verificarTempoGuarda')]//td[7]/a[2] | 
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[contains(.,\'MdGdAgendamentoRN :: verificarTempoGuarda\')]//td[7]/a[2]").click()
    # 12 | webdriverChooseOkOnVisibleConfirmation |  | 
    self.driver.switch_to.alert.accept()
    # 13 | waitForElementVisible | xpath=//div[@id='divInfraAreaTabela']/table/tbody/tr[contains(.,'MdGdAgendamentoRN :: verificarTempoGuarda')]//td[6][text()="Sucesso"] | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[contains(.,\'MdGdAgendamentoRN :: verificarTempoGuarda\')]//td[6][text()=\"Sucesso\"]")))
  
