# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test05SEIGDAvaliacao():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["SELENIUMTEST_MODALIDADE"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor=os.environ["SELENIUMTEST_SELENIUMHOST_URL"], desired_capabilities=DesiredCapabilities.CHROME)

    if ((not 'maximizar_screen' in os.environ) or os.environ['maximizar_screen'] == 'true'):
        self.driver.maximize_window()

    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_0510Avaliacao(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (20 registros):"
    self.vars["root"] = self.driver.current_window_handle
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "//img[@title=\'Enviar para Correção\']").click()
    self.vars["win7640"] = self.wait_for_window(2000)
    self.driver.switch_to.alert.accept()
    self.driver.switch_to.window(self.vars["win7640"])
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtObservacaoDevolucao")))
    self.driver.find_element(By.ID, "txtObservacaoDevolucao").click()
    self.driver.find_element(By.ID, "txtObservacaoDevolucao").send_keys("teste")
    self.driver.find_element(By.NAME, "sbmDevolver").click()
    time.sleep(3)
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (19 registros):"
  
  def test_0520VerificaVolta(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//a[contains(., '99993.000001')]/../../td/a/img[@title='Concluir Edição']")))
    #assert self.driver.find_element(By.CSS_SELECTOR, "b").text == "Devolvido para correção"
    assert self.driver.find_element(By.XPATH, "//a[contains(., '99993.000001' )]").text.find("99993.000001") > -1 
    #self.driver.find_element(By.XPATH, "//img[@title=\'Editar Processo\']").click()
    #self.driver.switch_to.alert.accept()
    self.driver.find_element(By.LINK_TEXT, "Controle de Processos").click()
    element = self.driver.find_element(By.XPATH, "//a[contains(., '99993.000001' )]")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//a[contains(., '99993.000001' )]").click()
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Consultar/Alterar Processo\']")))
    self.driver.find_element(By.XPATH, "//img[@alt=\'Consultar/Alterar Processo\']").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txaObservacoes")))
    self.driver.find_element(By.ID, "txaObservacoes").click()
    self.driver.find_element(By.ID, "txaObservacoes").send_keys("obs alterado")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"btnSalvar\"]")))
    self.driver.find_element(By.XPATH, "//*[@id=\"btnSalvar\"]").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.XPATH, "//a[@id='lnkInfraMenuSistema']/../../../div[@id='divInfraBarraSistemaPadraoD']/div/a|//div[@id='divInfraBarraSistemaPadrao']/div/div/button").click()
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(3)").text == "teste arquivo"
    self.driver.find_element(By.CSS_SELECTOR, "td .infraImg").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.ID, "divInfraAreaTelaD").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
  
  def test_0530VerificarRetorno(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//button[@id='sbmPesquisar']")))
    self.driver.find_element(By.XPATH, "//button[@id='sbmPesquisar']").click()
    
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (20 registros):"
  
  def test_0540MandaListagemEliminacao(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    self.driver.find_element(By.XPATH, "//img[@title=\'Gerar Listagem de Eliminação\'][1]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//img[@title=\'Gerar Listagem de Eliminação\'][1]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//img[@title=\'Gerar Listagem de Eliminação\'][1]").click()
    self.driver.switch_to.alert.accept()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraBarraLocalizacao\"]")))
  
  def test_0550MandaListagemEliminacao(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Listagens de Eliminação\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    #self.driver.find_element(By.XPATH, "//img[@title=\'Adicionar Observação e/ou Justificativa\'][1]").click()
    #self.driver.switch_to.alert.accept()
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnExcluir").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.ID, "divInfraAreaTabela").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    self.driver.find_element(By.XPATH, "//img[@title=\'Gerar Listagem de Eliminação\'][1]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//img[@title=\'Gerar Listagem de Eliminação\'][1]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//img[@title=\'Gerar Listagem de Eliminação\'][1]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//img[@title=\'Gerar Listagem de Eliminação\'][1]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//img[@title=\'Gerar Listagem de Eliminação\'][1]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Listagens de Eliminação\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//span[. = 'Preparação da Listagem']")))    
    self.driver.find_element(By.XPATH, "//span[. = 'Preparação da Listagem' ]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Lista de Processos (5 registros):"
    #self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//button[@id='sbmPesquisar']")))
    self.driver.find_element(By.XPATH, "//button[@id='sbmPesquisar']").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (15 registros):"
  
  def test_0560AlteraObservacao1(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Listagens de Eliminação\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "(//img[@title=\'Adicionar Observação e/ou Justificativa\'])[1]").click()
    self.vars["win644"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win644"])
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txaObservacao")))
    self.driver.find_element(By.ID, "txaObservacao").click()
    self.driver.find_element(By.ID, "txaObservacao").send_keys("observacao1")
    self.driver.find_element(By.NAME, "sbmObservar").click()
  
  def test_0565AlteraObservacao2(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Listagens de Eliminação\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "(//img[@title=\'Adicionar Observação e/ou Justificativa\'])[2]").click()
    self.vars["win3874"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win3874"])
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txaObservacao")))
    self.driver.find_element(By.ID, "txaObservacao").click()
    self.driver.find_element(By.ID, "txaObservacao").send_keys("observacao 2")
    self.driver.find_element(By.NAME, "sbmObservar").click()
  
  def test_0570AlteraObservacao3(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Listagens de Eliminação\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "(//img[@title=\'Adicionar Observação e/ou Justificativa\'])[3]").click()
    self.vars["win3874"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win3874"])
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txaObservacao")))
    self.driver.find_element(By.ID, "txaObservacao").click()
    self.driver.find_element(By.ID, "txaObservacao").send_keys("observacao 4")
    self.driver.find_element(By.NAME, "sbmObservar").click()
  
  def test_0575AlteraObservacao3Conserta(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Listagens de Eliminação\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "(//img[@title=\'Adicionar Observação e/ou Justificativa\'])[3]")))
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "(//img[@title=\'Adicionar Observação e/ou Justificativa\'])[3]").click()
    self.vars["win3874"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win3874"])
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txaObservacao")))
    self.driver.find_element(By.ID, "txaObservacao").click()
    self.driver.find_element(By.ID, "txaObservacao").send_keys("observacao 3")
    self.driver.find_element(By.NAME, "sbmObservar").click()
  
