# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test09SEIGDEliminarProcsDocs():
  def setup_method(self, method):
      if ("LOCAL" == os.environ["SELENIUMTEST_MODALIDADE"]):
          self.driver = webdriver.Chrome()
      else:
          self.driver = webdriver.Remote(command_executor=os.environ["SELENIUMTEST_SELENIUMHOST_URL"], desired_capabilities=DesiredCapabilities.CHROME)
      
      if ((not 'maximizar_screen' in os.environ) or os.environ['maximizar_screen'] == 'true'):
        self.driver.maximize_window()
      
      self.driver.implicitly_wait(5)
      self.vars = {}
  
  def teardown_method(self, method):
      self.driver.quit()
    
  

  
  def test_0910EliminarProc(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[.='Listagens de Eliminação']/..").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão das Listagens").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[7]/a[3]")))
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[7]/a[3]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "imgInfraCheck")))
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "//*[@id=\"btnEliminar\"]").click()
    self.vars["win6388"] = self.wait_for_window(2)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win6388"])
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selCargoFuncao")))
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Assessor(a)']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    dropdown = self.driver.find_element(By.ID, "selVeiculoPublicacao")
    dropdown.find_element(By.XPATH, "//option[. = 'Boletim de Serviço Eletrônico']").click()
    self.driver.find_element(By.ID, "selVeiculoPublicacao").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selSecaoImprensaNacional")))
    dropdown = self.driver.find_element(By.ID, "selSecaoImprensaNacional")
    dropdown.find_element(By.XPATH, "//option[. = '2']").click()
    self.driver.find_element(By.ID, "selSecaoImprensaNacional").click()
    self.driver.find_element(By.ID, "txtPagina").click()
    self.driver.find_element(By.ID, "txtPagina").send_keys("10")
    self.driver.find_element(By.ID, "txtData").click()
    self.driver.find_element(By.ID, "txtData").send_keys("01/02/2020")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "sbmEliminar").click()
    time.sleep(5)
    self.driver.switch_to.window(self.vars["root"])
    time.sleep(5)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "divInfraBarraLocalizacao")))
    assert self.driver.find_element(By.ID, "divInfraBarraLocalizacao").text == "Gestão das Listagens de Eliminação"
    self.driver.find_element(By.ID, "txtPesquisaRapida").click()
    self.driver.find_element(By.ID, "txtPesquisaRapida").send_keys("99993.000033/2021-14")
    self.driver.find_element(By.ID, "txtPesquisaRapida").send_keys(Keys.ENTER)
    time.sleep(5)
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "divInformacao")))
    elements = self.driver.find_elements(By.XPATH, "//div[contains(.,\'andamentos abertos\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//div[contains(.,\'Processo eliminado\')]")
    assert len(elements) > 0
  
