# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1800Anexado():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["SELENIUMTEST_MODALIDADE"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor=os.environ["SELENIUMTEST_SELENIUMHOST_URL"], desired_capabilities=DesiredCapabilities.CHROME)

    if ((not 'maximizar_screen' in os.environ) or os.environ['maximizar_screen'] == 'true'):
        self.driver.maximize_window()

    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    #time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_cadastrarProcessosarrecadacao(self):
    
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivistaorg2")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivistaorg2")
    self.driver.find_element(By.ID, "selOrgao").click()
    dropdown = self.driver.find_element(By.ID, "selOrgao")
    dropdown.find_element(By.XPATH, "//option[. = 'Org2']").click()
    self.driver.find_element(By.ID, "Acessar").click()

    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Iniciar Processo")))
    self.driver.find_element(By.LINK_TEXT, "Iniciar Processo").click()
    self.vars["error"] = len(self.driver.find_elements(By.XPATH, "//a[contains(text(), \'Arrecadação: Receita\')]"))
    if self.driver.execute_script("return (arguments[0]==0)", self.vars["error"]):
      self.driver.find_element(By.ID, "imgExibirTiposProcedimento").click()

    self.driver.find_element(By.LINK_TEXT, "Arrecadação: Receita").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtDescricao")))
    self.driver.find_element(By.ID, "txtDescricao").send_keys("teste anexo")
    self.driver.find_element(By.ID, "lblPublico").click()
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraBarraComandosInferior > #btnSalvar > .infraTeclaAtalho").click()
    self.driver.switch_to.frame(0)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//a[contains(., \"998\")]")))
    self.driver.find_element(By.XPATH, "//a[contains(., \"998\")]").click()
    time.sleep(2)
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[contains(@title,\'Incluir Documento\')]")))
    self.driver.find_element(By.XPATH, "//*[contains(@title,\'Incluir Documento\')]").click()
    self.vars["error"] = len(self.driver.find_elements(By.XPATH, "//a[contains(text(), \'Despacho\')]"))
    if self.driver.execute_script("return (arguments[0]==0)", self.vars["error"]):
      self.driver.find_element(By.ID, "imgExibirSeries").click()

    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Despacho")))
    self.driver.find_element(By.LINK_TEXT, "Despacho").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "lblPublico")))
    self.driver.find_element(By.ID, "lblPublico").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "btnSalvar").click()
    self.vars["win3408"] = self.wait_for_window(5)
    self.vars["root"] = self.driver.current_window_handle
    time.sleep(2)
    self.driver.switch_to.window(self.vars["win3408"])
    time.sleep(2)
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    time.sleep(2)
    self.driver.switch_to.frame(0)
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Concluir Processo\']")))
    time.sleep(2)
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(0)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//a[contains(., \"998\")]")))
    self.driver.find_element(By.XPATH, "//a[contains(., \"998\")]").click()
    time.sleep(2)
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[contains(@title,'Consultar/Alterar Processo')]")))
    self.driver.find_element(By.XPATH, "//*[contains(@title,'Consultar/Alterar Processo')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selAssuntos")))
    #dropdown = self.driver.find_element(By.ID, "selAssuntos")
    #dropdown.find_element(By.XPATH, "//option[. = '019.01 - INFORMAÇÕES SOBRE O ÓRGÃO (inclusive Pedidos de Informações sobre as Funções e Atividades do Órgão e os Serviços que presta)']").click()
    #self.driver.find_element(By.ID, "imgRemoverAssuntos").click()
    self.driver.find_element(By.ID, "txtAssunto").click()
    self.driver.find_element(By.ID, "txtAssunto").send_keys("23.03")
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "selAssuntos")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    time.sleep(2)

    self.driver.find_element(By.ID, "txtAssunto").click()
    self.driver.find_element(By.ID, "txtAssunto").send_keys("010.2")
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "selAssuntos")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    time.sleep(2)

    self.driver.find_element(By.ID, "btnSalvar").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#divInfraAreaTabela > label")
    assert len(elements) == 0
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[contains(@title,'Concluir Processo')]")))


  def test_cadastrarProcessosacessoinf(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivistaorg2")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivistaorg2")
    self.driver.find_element(By.ID, "selOrgao").click()
    dropdown = self.driver.find_element(By.ID, "selOrgao")
    dropdown.find_element(By.XPATH, "//option[. = 'Org2']").click()
    self.driver.find_element(By.ID, "Acessar").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Iniciar Processo")))
    self.driver.find_element(By.LINK_TEXT, "Iniciar Processo").click()
    self.driver.find_element(By.ID, "imgExibirTiposProcedimento").click()
    self.driver.find_element(By.LINK_TEXT, "Acesso à Informação: Demanda do e-SIC").click()
    self.driver.find_element(By.ID, "txtDescricao").send_keys("teste arquivo")
    self.driver.find_element(By.CSS_SELECTOR, "#divOptPublico .infraRadioLabel").click()
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraBarraComandosInferior > #btnSalvar > .infraTeclaAtalho").click()
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Incluir Documento\']")))
    self.driver.find_element(By.XPATH, "//img[@alt=\'Incluir Documento\']").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Despacho")))
    self.driver.find_element(By.LINK_TEXT, "Despacho").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#divOptPublico .infraRadioLabel")))
    self.driver.find_element(By.CSS_SELECTOR, "#divOptPublico .infraRadioLabel").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "btnSalvar").click()
    self.vars["win3408"] = self.wait_for_window(10)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win3408"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.switch_to.frame(0)
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(1)
    self.driver.switch_to.window(self.vars["root"])
    self.driver.switch_to.frame(0)
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.XPATH, "//span").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Anexar Processo\']")))
    self.driver.find_element(By.XPATH, "//img[@alt=\'Anexar Processo\']").click()
    self.driver.find_element(By.ID, "txtProtocolo").send_keys("99897.000003")
    self.driver.find_element(By.CSS_SELECTOR, "#btnPesquisar > .infraTeclaAtalho").click()
    self.driver.find_element(By.ID, "sbmAnexar").click()    
    self.driver.switch_to.alert.accept()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//a[. = '99897.000003/2037-63'  and @title='Arrecadação: Receita' ]")))
    #time.sleep(5)
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.XPATH, "//span").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(1)

    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Arquivar Processo\']"))) 
    self.driver.find_element(By.XPATH, "//img[@alt=\'Arquivar Processo\']").click()
    self.driver.find_element(By.ID, "selJustificativa").click()
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Arquivamento 01']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Assessor(a)']").click()
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivistaorg2")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "btnAssinar").click()
    self.vars["win1700"] = self.wait_for_window(5)
    self.driver.switch_to.window(self.vars["win1700"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//div[@id='divInfraBarraSistemaPadrao']//div//div/a[@id='lnkInfraUnidade']")))
    self.driver.find_element(By.XPATH, "//div[@id='divInfraBarraSistemaPadrao']//div//div/a[@id='lnkInfraUnidade']").click()
    # self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    # time.sleep(2)
    # WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//button[@id='sbmPesquisar']")))
    # self.driver.find_element(By.XPATH, "//button[@id='sbmPesquisar']").click()
    # time.sleep(2)
    # WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//td[contains(.,'2 anos, 0 meses e 0 dias.')]")))
    # elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'2 anos, 0 meses e 0 dias.\')]")
    # assert len(elements) > 0
