# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test03GDPendenciasArquivamento():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_010PendenciasArquivamentoAnotacao(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//td[contains(.,\'000002\')]/../td[9]/a[3]")))
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "//td[contains(.,\'000002\')]/../td[9]/a[3]").click()
    self.vars["win9237"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win9237"])
    self.driver.find_element(By.ID, "txaAnotacao").click()
    self.driver.find_element(By.ID, "txaAnotacao").send_keys("Anotacao01")
    self.driver.find_element(By.NAME, "sbmAnotar").click()
  
  def test_011PendenciasArquivamentoAnotacao(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "//td[contains(.,\'000003\')]/../td[9]/a[3]").click()
    self.vars["win9237"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win9237"])
    self.driver.find_element(By.ID, "txaAnotacao").send_keys("Anotacao02")
    self.driver.find_element(By.NAME, "sbmAnotar").click()
  
  def test_012PendenciasArquivamentoAnotacao(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "//td[contains(.,\'000004\')]/../td[9]/a[3]").click()
    self.vars["win9237"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win9237"])
    self.driver.find_element(By.ID, "txaAnotacao").click()
    self.driver.find_element(By.ID, "txaAnotacao").send_keys("alt")
    self.driver.find_element(By.NAME, "sbmAnotar").click()
  
  def test_020PendenciasArquivamentoReabrirMassa(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "sbmReabrir").click()
    self.driver.switch_to.alert.accept()
    assert self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/caption").text == "Lista de Pendências de Arquivamento (5 registros):"
    self.driver.find_element(By.LINK_TEXT, "Controle de Processos").click()
    self.driver.find_element(By.ID, "imgGeradosCheck").click()
    self.driver.find_element(By.CSS_SELECTOR, ".botaoSEI:nth-child(6) > .infraCorBarraSistema").click()
  
  def test_030PendenciasArquivamentoReabrirUnico(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    self.driver.find_element(By.XPATH, "//td[contains(.,\'99993.000001/2020\')]/../td[9]/a[1]").click()
    self.driver.switch_to.alert.accept()
    elements = self.driver.find_elements(By.XPATH, "//a[starts-with(.,\'99993.000001\') and contains(.,\'9\')]")
    assert len(elements) == 0
  
  def test_040PendenciasArquivamentoArquivarMassa(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "sbmArquivar").click()
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Arquivamento 01']").click()
    self.driver.find_element(By.ID, "selJustificativa").click()
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Assessor(a)']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmSalvar").click()
    assert self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/caption").text == "Lista de Pendências de Arquivamento (5 registros):"
  
  def test_050PendenciasArquivamentoArquivarUnico(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    self.driver.find_element(By.XPATH, "//td[contains(.,\'99993.000056/\')]/../td[9]/a[2]").click()
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Arquivamento 01']").click()
    self.driver.find_element(By.ID, "selJustificativa").click()
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Assessor(a)']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmSalvar").click()
    elements = self.driver.find_elements(By.XPATH, "//a[starts-with(.,\'99993.000056\') and contains(.,\'9\')]")
    assert len(elements) == 0
  
  def test_060ArquivoUnidadeDesarquivarMassa(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "sbmDesarquivar").click()
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Desarquivamento 02']").click()
    self.driver.find_element(By.ID, "selJustificativa").click()
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Gestor de Contrato']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmSalvar").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos Arquivados (1 registro):"
  
  def test_070ArquivoUnidadeDesarquivarUnico(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "td .infraImg")))
    self.driver.find_element(By.CSS_SELECTOR, "td .infraImg").click()
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Desarquivamento 01']").click()
    self.driver.find_element(By.ID, "selJustificativa").click()
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Gestor de Contrato']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmSalvar").click()
    self.driver.switch_to.alert.accept()
    self.driver.switch_to.frame(0)
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "span:nth-child(2)")))
    assert self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(2)").text == "Consultar Andamento"
    time.sleep(1)
  
  def test_080PendenciasArquivamentoArquivarMassa(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Controle de Processos").click()
    self.driver.find_element(By.ID, "imgGeradosCheck").click()
    self.driver.find_element(By.CSS_SELECTOR, ".botaoSEI:nth-child(6) > .infraCorBarraSistema").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "sbmArquivar").click()
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Arquivamento 01']").click()
    self.driver.find_element(By.ID, "selJustificativa").click()
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Assessor(a)']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmSalvar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Pendências de Arquivamento (6 registros):"
  
  def test_090PendenciasArquivamentoArquivarUnico(self):
    self.driver.get("http://seigd.intra.planejamento/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista01")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    self.driver.find_element(By.XPATH, "//td[contains(.,\'99993.000056/\')]/../td[9]/a[2]").click()
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Arquivamento 01']").click()
    self.driver.find_element(By.ID, "selJustificativa").click()
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Assessor(a)']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista01")
    self.driver.find_element(By.ID, "sbmSalvar").click()
    elements = self.driver.find_elements(By.XPATH, "//a[starts-with(.,\'99993.000056\') and contains(.,\'9\')]")
    assert len(elements) == 0
  
