# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test00ConfigSIP():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sIPCriarMontarUnidades(self):
    self.driver.get("http://seigd.intra.planejamento//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SIP")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'main-menu\']/li[8]/a").click()
    self.driver.find_element(By.LINK_TEXT, "Nova").click()
    dropdown = self.driver.find_element(By.ID, "selOrgao")
    dropdown.find_element(By.XPATH, "//option[. = 'ME']").click()
    self.driver.find_element(By.ID, "selOrgao").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "txtSigla")))
    self.driver.find_element(By.ID, "txtSigla").click()
    self.driver.find_element(By.ID, "txtSigla").send_keys("ArquivoGeral02")
    self.driver.find_element(By.ID, "txtDescricao").click()
    self.driver.find_element(By.ID, "txtDescricao").send_keys("ArquivoGeral02")
    self.driver.find_element(By.NAME, "sbmCadastrarUnidade").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'main-menu\']/li[7]/a").click()
    self.driver.find_element(By.LINK_TEXT, "Montar").click()
    dropdown = self.driver.find_element(By.ID, "selHierarquia")
    dropdown.find_element(By.XPATH, "//option[. = 'SEI']").click()
    self.driver.find_element(By.ID, "selHierarquia").click()
    self.driver.find_element(By.ID, "btnNova").click()
    dropdown = self.driver.find_element(By.ID, "selUnidade")
    dropdown.find_element(By.XPATH, "//option[. = 'ArquivoGeral02']").click()
    self.driver.find_element(By.ID, "selUnidade").click()
    self.driver.find_element(By.ID, "txtDataInicio").click()
    self.driver.find_element(By.ID, "txtDataInicio").send_keys("01/01/2019")
    self.driver.find_element(By.NAME, "sbmCadastrarHierarquiaUnidade").click()
  
