# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test01ConfigSEI():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["local_do_teste"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_unidadesArquivamento(self):
    # Test name: UnidadesArquivamento
    # Step # | name | target | value
    # 1 | open | sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8= | 
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    # 2 | waitForElementEditable | id=txtUsuario | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtUsuario")))
    # 3 | type | id=txtUsuario | teste
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    # 4 | type | id=pwdSenha | teste
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    # 5 | click | id=Acessar | 
    self.driver.find_element(By.ID, "Acessar").click()
    # 6 | waitForElementVisible | xpath=//*[text()="Administração"] | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[text()=\"Administração\"]")))
    # 7 | click | xpath=//*[text()="Administração"] | 
    self.driver.find_element(By.XPATH, "//*[text()=\"Administração\"]").click()
    # 8 | click | xpath=//*[text()="Gestão Documental"] | 
    self.driver.find_element(By.XPATH, "//*[text()=\"Gestão Documental\"]").click()
    # 9 | click | xpath=//*[text()="Unidades de Arquivamento"] | 
    self.driver.find_element(By.XPATH, "//*[text()=\"Unidades de Arquivamento\"]").click()
    # 10 | click | linkText=Listar | 
    self.driver.find_element(By.LINK_TEXT, "Listar").click()
    # 11 | click | id=btnNova | 
    self.driver.find_element(By.ID, "btnNova").click()
    # 12 | click | id=selUnidadeDestino | 
    self.driver.find_element(By.ID, "selUnidadeDestino").click()
    # 13 | select | id=selUnidadeDestino | label=ArquivoGeral02 - ArquivoGeral02
    dropdown = self.driver.find_element(By.ID, "selUnidadeDestino")
    dropdown.find_element(By.XPATH, "//option[. = 'ArquivoGeral02 - ArquivoGeral02']").click()
    # 14 | click | id=txtUnidadeOrigem | 
    self.driver.find_element(By.ID, "txtUnidadeOrigem").click()
    # 15 | type | id=txtUnidadeOrigem | TESTE_1_1
    self.driver.find_element(By.ID, "txtUnidadeOrigem").send_keys("TESTE_1_1")
    # 16 | waitForElementVisible | css=#divInfraAjaxtxtUnidadeOrigem li:nth-child(3) > a | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#divInfraAjaxtxtUnidadeOrigem li:nth-child(3) > a")))
    # 17 | mouseDown | css=#divInfraAjaxtxtUnidadeOrigem li:nth-child(3) > a | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#divInfraAjaxtxtUnidadeOrigem li:nth-child(3) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 18 | mouseUp | css=#selUnidadesOrigem > option | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#selUnidadesOrigem > option")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 19 | click | css=body | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 20 | click | name=sbmCadastrarUnidadeArquivamento | 
    self.driver.find_element(By.NAME, "sbmCadastrarUnidadeArquivamento").click()
  
  def test_enderecoUnidades(self):
    # Test name: EnderecoUnidades
    # Step # | name | target | value
    # 1 | open | sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8= | 
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    # 2 | waitForElementEditable | id=txtUsuario | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtUsuario")))
    # 3 | type | id=txtUsuario | teste
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    # 4 | click | id=pwdSenha | 
    self.driver.find_element(By.ID, "pwdSenha").click()
    # 5 | type | id=pwdSenha | teste
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    # 6 | click | id=Acessar | 
    self.driver.find_element(By.ID, "Acessar").click()
    # 7 | waitForElementVisible | xpath=//*[text()="Administração"] | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[text()=\"Administração\"]")))
    # 8 | click | xpath=//*[text()="Administração"] | 
    self.driver.find_element(By.XPATH, "//*[text()=\"Administração\"]").click()
    # 9 | click | xpath=//*[text()="Unidades"] | 
    self.driver.find_element(By.XPATH, "//*[text()=\"Unidades\"]").click()
    # 10 | click | linkText=Listar | 
    self.driver.find_element(By.LINK_TEXT, "Listar").click()
    # 11 | click | xpath=(//img[@alt='Alterar Unidade'])[3] | 
    self.driver.find_element(By.XPATH, "(//img[@alt=\'Alterar Unidade\'])[3]").click()
    # 12 | click | id=txtCodigoSei | 
    self.driver.find_element(By.ID, "txtCodigoSei").click()
    # 13 | type | id=txtCodigoSei | 96
    self.driver.find_element(By.ID, "txtCodigoSei").send_keys("96")
    # 14 | waitForElementVisible | xpath=//*[@id="divInfraBarraComandosSuperior"]/button[1] | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraBarraComandosSuperior\"]/button[1]")))
    # 15 | click | xpath=//*[@id="divInfraBarraComandosSuperior"]/button[1] | 
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraBarraComandosSuperior\"]/button[1]").click()
    # 16 | waitForElementVisible | xpath=(//img[@alt='Alterar Unidade'])[3] | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "(//img[@alt=\'Alterar Unidade\'])[3]")))
    # 17 | click | xpath=(//img[@alt='Alterar Unidade'])[3] | 
    self.driver.find_element(By.XPATH, "(//img[@alt=\'Alterar Unidade\'])[3]").click()

    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "imgAlterarContato").click()
    #self.vars["win4521"] = self.wait_for_window(2000)
    #self.vars["root"] = self.driver.current_window_handle
    #self.driver.switch_to.window(self.vars["win4521"])
    self.driver.switch_to.frame(0)
    WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "txtEndereco")))
    self.driver.find_element(By.ID, "txtEndereco").click()
    self.driver.find_element(By.ID, "txtEndereco").send_keys("Endereco01")
    dropdown = self.driver.find_element(By.ID, "selPais")
    dropdown.find_element(By.XPATH, "//option[. = 'Brasil']").click()
    self.driver.find_element(By.ID, "selPais").click()
    dropdown = self.driver.find_element(By.ID, "selUf")
    dropdown.find_element(By.XPATH, "//option[. = 'DF']").click()
    self.driver.find_element(By.ID, "selUf").click()
    dropdown = self.driver.find_element(By.ID, "selCidade")
    dropdown.find_element(By.XPATH, "//option[. = 'Brasília']").click()
    self.driver.find_element(By.ID, "selCidade").click()
    self.driver.find_element(By.ID, "txtCep").click()
    self.driver.find_element(By.ID, "txtCep").send_keys("00000-000")
    self.driver.find_element(By.NAME, "sbmAlterarContato").click()
    time.sleep(2)
    #self.driver.switch_to.window(self.vars["root"])
    self.driver.switch_to.default_content()
    time.sleep(2)
  
