# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test06SEIGDListasEliminacaoGestao():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path="/home/seges/projetos/sei/chromedriver")
    self.driver.implicitly_wait(5)
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_0610GerarListagem(self):
    self.driver.get("http://org1-http:8000//sip/login.php?sigla_orgao_sistema=ABC&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    #self.driver.find_element(By.XPATH, "//span[contains(text(),'Gestão Documental')]/..").click()
    self.driver.find_element(By.XPATH, "//*[@id='infraMenu']/li[21]/a").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]/..").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "chkInfraItem0")))
    self.driver.find_element(By.ID, "chkInfraItem0").click()
    self.driver.find_element(By.ID, "btnGerarListagem").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnGerarListagem").click()
    self.driver.find_element(By.XPATH, "//*[@id='infraMenu']/li[21]/a").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]").click()
    self.driver.find_element(By.XPATH, "Gestão das Listagens").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Listagens de Eliminacao (2 registros):"
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[3]/td[3]").click()
    elements = self.driver.find_elements(By.XPATH, "//td[starts-with(.,\'99994.000001\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[3]").click()
    elements = self.driver.find_elements(By.XPATH, "//td[starts-with(.,\'99994.000002\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[7]/a[1]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (4 registros):"
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, "#lnkSairSistema > .infraImg").click()
    self.driver.get("http://org1-http:8000//sip/login.php?sigla_orgao_sistema=ABC&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//*[@id='infraMenu']/li[21]/a").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]/..").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão das Listagens").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[3]/td[7]/a[1]/img")))
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[3]/td[7]/a[1]/img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos (1 registro):"
    self.driver.find_element(By.ID, "btnCancelar").click()
  
  def test_0620AlterarListagem(self):
    self.driver.get("http://org1-http:8000//sip/login.php?sigla_orgao_sistema=ABC&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//*[@id='infraMenu']/li[21]/a").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(),'Listagens de Eliminação')]").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão das Listagens").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[7]/a[2]").click()
    self.driver.switch_to.alert.accept()
    time.sleep(5000)
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[7]/a[3]").click()
    self.driver.find_element(By.ID, "chkInfraItem0").click()
    self.driver.find_element(By.ID, "btnExcluirListagem").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Lista de Processos (3 registros):"
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnExcluirListagem").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.ID, "divInfraAreaTelaD").click()
    self.driver.find_element(By.ID, "frmPrepararListagemEliminacao").click()
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
    self.driver.find_element(By.XPATH, "//*[@id=\"btnFechar\"]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[7]/a[2]").click()
    self.driver.find_element(By.ID, "chkInfraItem0").click()
    self.driver.find_element(By.ID, "btnAdicionarListagem").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Lista de Processos (3 registros):"
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnAdicionarListagem").click()
    self.driver.find_element(By.ID, "btnFechar").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[7]/a[4]").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Listagens de Eliminacao (2 registros):"
  
