# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test07SEIGDAvaliacaoRecolhimento():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["SELENIUMTEST_MODALIDADE"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor=os.environ["SELENIUMTEST_SELENIUMHOST_URL"], desired_capabilities=DesiredCapabilities.CHROME)
    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    #time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_0740MandaListagemRecolhimento(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a/img").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a/img").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a/img").click()
    self.driver.switch_to.alert.accept()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraBarraLocalizacao\"]")))
  
  def test_0750MandaListagemRecolhimento(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[.='Listagens de Recolhimento']/..").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    #self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a[2]/img").click()
    #self.driver.switch_to.alert.accept()
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnExcluir").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    self.driver.find_element(By.ID, "divInfraAreaTabela").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
    #self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a/img").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a/img").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a/img").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a/img").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a/img").click()
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[.='Listagens de Recolhimento']/..").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//button[@id='sbmPesquisar']")))
    self.driver.find_element(By.XPATH, "//button[@id='sbmPesquisar']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Lista de Processos (5 registros):"
    #self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//button[@id='sbmPesquisar']")))
    self.driver.find_element(By.XPATH, "//button[@id='sbmPesquisar']").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos Arquivados (91 registros - 1 a 50):"
  
  def test_0760AlteraObservacao1(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[.='Listagens de Recolhimento']/..").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[9]/a/img").click()
    self.vars["win644"] = self.wait_for_window(4)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win644"])
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txaObservacao")))
    self.driver.find_element(By.ID, "txaObservacao").click()
    self.driver.find_element(By.ID, "txaObservacao").send_keys("observacao1")
    self.driver.find_element(By.NAME, "sbmObservar").click()
  
  def test_0765AlteraObservacao2(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[.='Listagens de Recolhimento']/..").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "(//img[@title=\'Adicionar Observação e/ou Justificativa\'])[2]").click()
    self.vars["win3874"] = self.wait_for_window(4)
    self.driver.switch_to.window(self.vars["win3874"])
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txaObservacao")))
    self.driver.find_element(By.ID, "txaObservacao").click()
    self.driver.find_element(By.ID, "txaObservacao").send_keys("observacao 2")
    self.driver.find_element(By.NAME, "sbmObservar").click()
  
  def test_0770AlteraObservacao3(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[.='Listagens de Recolhimento']/..").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "(//img[@title=\'Adicionar Observação e/ou Justificativa\'])[3]").click()
    self.vars["win3874"] = self.wait_for_window(4)
    self.driver.switch_to.window(self.vars["win3874"])
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txaObservacao")))
    self.driver.find_element(By.ID, "txaObservacao").click()
    self.driver.find_element(By.ID, "txaObservacao").send_keys("observacao 4")
    self.driver.find_element(By.NAME, "sbmObservar").click()
  
  def test_0775AlteraObservacao3Conserta(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.XPATH, "//span[.='Listagens de Recolhimento']/..").click()
    self.driver.find_element(By.LINK_TEXT, "Preparação da Listagem").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "(//img[@title=\'Adicionar Observação e/ou Justificativa\'])[3]")))
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "(//img[@title=\'Adicionar Observação e/ou Justificativa\'])[3]").click()
    self.vars["win3874"] = self.wait_for_window(4)
    self.driver.switch_to.window(self.vars["win3874"])
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txaObservacao")))
    self.driver.find_element(By.ID, "txaObservacao").click()
    self.driver.find_element(By.ID, "txaObservacao").send_keys("observacao 3")
    self.driver.find_element(By.NAME, "sbmObservar").click()
  
