# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test01ConfigSEI():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["SELENIUMTEST_MODALIDADE"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor=os.environ["SELENIUMTEST_SELENIUMHOST_URL"], desired_capabilities=DesiredCapabilities.CHROME)
    
    if ((not 'maximizar_screen' in os.environ) or os.environ['maximizar_screen'] == 'true'):
        self.driver.maximize_window()
    
    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_unidadesArquivamento(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "Acessar").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[text()=\"Administração\"]")))
    self.driver.find_element(By.XPATH, "//*[text()=\"Administração\"]").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Gestão Documental\"]").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Unidades de Arquivamento\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Listar").click()
    self.driver.find_element(By.ID, "btnNova").click()
    self.driver.find_element(By.ID, "selUnidadeDestino").click()
    dropdown = self.driver.find_element(By.ID, "selUnidadeDestino")
    dropdown.find_element(By.XPATH, "//option[. = 'ArquivoGeral02 - ArquivoGeral02']").click()
    self.driver.find_element(By.ID, "txtUnidadeOrigem").click()
    self.driver.find_element(By.ID, "txtUnidadeOrigem").send_keys("TESTE_1_1")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#divInfraAjaxtxtUnidadeOrigem li:nth-child(3) > a")))
    element = self.driver.find_element(By.CSS_SELECTOR, "#divInfraAjaxtxtUnidadeOrigem li:nth-child(3) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "#selUnidadesOrigem > option")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.NAME, "sbmCadastrarUnidadeArquivamento").click()
  
  def test_enderecoUnidades(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "Acessar").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[text()=\"Administração\"]")))
    self.driver.find_element(By.XPATH, "//*[text()=\"Administração\"]").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Unidades\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Listar").click()
    self.driver.find_element(By.XPATH, "(//img[@alt=\'Alterar Unidade\'])[3]").click()
    self.driver.find_element(By.ID, "txtCodigoSei").click()
    self.driver.find_element(By.ID, "txtCodigoSei").send_keys("96")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraBarraComandosSuperior\"]/button[1]")))
    self.driver.find_element(By.XPATH, "//*[@id=\"divInfraBarraComandosSuperior\"]/button[1]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "(//img[@alt=\'Alterar Unidade\'])[3]")))
    self.driver.find_element(By.XPATH, "(//img[@alt=\'Alterar Unidade\'])[3]").click()

    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "imgAlterarContato").click()
    #self.vars["win4521"] = self.wait_for_window(2000)
    #self.vars["root"] = self.driver.current_window_handle
    #self.driver.switch_to.window(self.vars["win4521"])
    self.driver.switch_to.frame(0)
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtEndereco")))
    self.driver.find_element(By.ID, "txtEndereco").click()
    self.driver.find_element(By.ID, "txtEndereco").send_keys("Endereco01")
    dropdown = self.driver.find_element(By.ID, "selPais")
    dropdown.find_element(By.XPATH, "//option[. = 'Brasil']").click()
    self.driver.find_element(By.ID, "selPais").click()
    dropdown = self.driver.find_element(By.ID, "selUf")
    dropdown.find_element(By.XPATH, "//option[. = 'DF']").click()
    self.driver.find_element(By.ID, "selUf").click()
    dropdown = self.driver.find_element(By.ID, "selCidade")
    dropdown.find_element(By.XPATH, "//option[. = 'Brasília']").click()
    self.driver.find_element(By.ID, "selCidade").click()
    self.driver.find_element(By.ID, "txtCep").click()
    self.driver.find_element(By.ID, "txtCep").send_keys("00000-000")
    self.driver.find_element(By.NAME, "sbmAlterarContato").click()
    time.sleep(2)
    #self.driver.switch_to.window(self.vars["root"])
    self.driver.switch_to.default_content()
    time.sleep(2)
  
