# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test00ConfigSIP():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["SELENIUMTEST_MODALIDADE"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor=os.environ["SELENIUMTEST_SELENIUMHOST_URL"], desired_capabilities=DesiredCapabilities.CHROME)
    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sIPCriarMontarUnidades(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SIP")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Unidades\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Nova").click()
    dropdown = self.driver.find_element(By.ID, "selOrgao")
    dropdown.find_element(By.XPATH, "//option[. = '"+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"']").click()
    self.driver.find_element(By.ID, "selOrgao").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtSigla")))
    self.driver.find_element(By.ID, "txtSigla").click()
    self.vars["unidade"] = "ArquivoGeral02"
    self.driver.find_element(By.ID, "txtSigla").send_keys(self.vars["unidade"])
    self.driver.find_element(By.ID, "txtDescricao").click()
    self.driver.find_element(By.ID, "txtDescricao").send_keys(self.vars["unidade"])
    self.driver.find_element(By.NAME, "sbmCadastrarUnidade").click()
    self.driver.find_element(By.XPATH, "//*[text()=\"Hierarquias\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Montar").click()
    dropdown = self.driver.find_element(By.ID, "selHierarquia")
    dropdown.find_element(By.XPATH, "//option[. = 'SEI']").click()
    self.driver.find_element(By.ID, "selHierarquia").click()
    self.driver.find_element(By.ID, "btnNova").click()
    dropdown = self.driver.find_element(By.ID, "selUnidade")
    dropdown.find_element(By.XPATH, "//option[. = '{}']".format(self.vars["unidade"])).click()
    self.driver.find_element(By.ID, "selUnidade").click()
    self.driver.find_element(By.ID, "txtDataInicio").click()
    self.driver.find_element(By.ID, "txtDataInicio").send_keys("01/01/2019")
    self.driver.find_element(By.NAME, "sbmCadastrarHierarquiaUnidade").click()
  
