# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1700Multiorgaos():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["local_do_teste"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.driver.maximize_window()
    self.driver.implicitly_wait(5)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_cadastrarProcessos(self):
    # Test name: CadastrarProcessos
    # Step # | name | target | value
    # 1 | open | /sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8= | 
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    # 2 | waitForElementVisible | id=txtUsuario | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "txtUsuario")))
    # 3 | click | id=txtUsuario | 
    self.driver.find_element(By.ID, "txtUsuario").click()
    # 4 | type | id=txtUsuario | arquivistaorg2
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivistaorg2")
    # 5 | waitForElementVisible | id=pwdSenha | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    # 6 | click | id=pwdSenha | 
    self.driver.find_element(By.ID, "pwdSenha").click()
    # 7 | type | id=pwdSenha | arquivistaorg2
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivistaorg2")
    # 8 | click | id=selOrgao | 
    self.driver.find_element(By.ID, "selOrgao").click()
    # 9 | select | id=selOrgao | label=Org2
    dropdown = self.driver.find_element(By.ID, "selOrgao")
    dropdown.find_element(By.XPATH, "//option[. = 'Org2']").click()
    # 10 | click | id=Acessar | 
    self.driver.find_element(By.ID, "Acessar").click()
    # 11 | waitForElementVisible | linkText=Iniciar Processo | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Iniciar Processo")))
    # 12 | click | linkText=Iniciar Processo | 
    self.driver.find_element(By.LINK_TEXT, "Iniciar Processo").click()
    # 13 | click | //*[@id="imgExibirTiposProcedimento"] | 
    self.driver.find_element(By.XPATH, "//*[@id=\"imgExibirTiposProcedimento\"]").click()
    # 14 | storeXpathCount | xpath=//a[contains(text(), 'Acesso à Informação: Demanda do e-SIC')] | error
    self.vars["error"] = len(self.driver.find_elements(By.XPATH, "//a[contains(text(), \'Acesso à Informação: Demanda do e-SIC\')]"))
    # 15 | if | ${error}==0 | 
    if self.driver.execute_script("return (arguments[0]==0)", self.vars["error"]):
      # 16 | click | //*[@id="imgExibirTiposProcedimento"] | 
      self.driver.find_element(By.XPATH, "//*[@id=\"imgExibirTiposProcedimento\"]").click()
      # 17 | end |  | 
    # 18 | click | linkText=Acesso à Informação: Demanda do e-SIC | 
    self.driver.find_element(By.LINK_TEXT, "Acesso à Informação: Demanda do e-SIC").click()
    # 19 | type | id=txtDescricao | teste arquivo
    self.driver.find_element(By.ID, "txtDescricao").send_keys("teste arquivo")
    # 20 | click | css=#divOptPublico .infraRadioLabel | 
    self.driver.find_element(By.CSS_SELECTOR, "#divOptPublico .infraRadioLabel").click()
    # 21 | click | css=#divInfraBarraComandosInferior > #btnSalvar > .infraTeclaAtalho | 
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraBarraComandosInferior > #btnSalvar > .infraTeclaAtalho").click()
    # 22 | selectFrame | index=1 | 
    self.driver.switch_to.frame(1)
    # 23 | waitForElementVisible | xpath=//img[@alt='Incluir Documento'] | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Incluir Documento\']")))
    # 24 | click | xpath=//img[@alt='Incluir Documento'] | 
    self.driver.find_element(By.XPATH, "//img[@alt=\'Incluir Documento\']").click()
    # 25 | waitForElementVisible | linkText=Despacho | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Despacho")))
    # 26 | click | linkText=Despacho | 
    self.driver.find_element(By.LINK_TEXT, "Despacho").click()
    # 27 | waitForElementVisible | css=#divOptPublico .infraRadioLabel | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#divOptPublico .infraRadioLabel")))
    # 28 | click | css=#divOptPublico .infraRadioLabel | 
    self.driver.find_element(By.CSS_SELECTOR, "#divOptPublico .infraRadioLabel").click()
    # 29 | click | id=btnSalvar | 
    self.vars["window_handles"] = self.driver.window_handles
    # 30 | storeWindowHandle | root | 
    self.driver.find_element(By.ID, "btnSalvar").click()
    # 31 | selectWindow | handle=${win3408} | 
    self.vars["win3408"] = self.wait_for_window(10000)
    # 32 | close |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 33 | selectWindow | handle=${root} | 
    self.driver.switch_to.window(self.vars["win3408"])
    # 34 | selectFrame | index=0 | 
    self.driver.close()
    # 35 | selectFrame | relative=parent | 
    self.driver.switch_to.window(self.vars["root"])
    # 36 | selectFrame | index=1 | 
    self.driver.switch_to.frame(0)
    # 37 | selectWindow | handle=${root} | 
    self.driver.switch_to.default_content()
    # 38 | selectFrame | index=0 | 
    self.driver.switch_to.frame(1)
    # 39 | selectFrame | relative=parent | 
    self.driver.switch_to.window(self.vars["root"])
    # 40 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 41 | click | xpath=//span | 
    self.driver.switch_to.default_content()
    # 42 | selectFrame | relative=parent | 
    self.driver.switch_to.frame(0)
    # 43 | selectFrame | index=1 | 
    self.driver.find_element(By.XPATH, "//span").click()
    # 44 | waitForElementVisible | xpath=//img[@alt='Concluir e Arquivar Processo'] | 30000
    self.driver.switch_to.default_content()
    # 45 | click | xpath=//img[@alt='Concluir e Arquivar Processo'] | 
    self.driver.switch_to.frame(1)
    # 46 | selectWindow | handle=${root} | 
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Concluir e Arquivar Processo\']")))
    # 47 | selectFrame | index=0 | 
    self.driver.find_element(By.XPATH, "//img[@alt=\'Concluir e Arquivar Processo\']").click()
    # 48 | selectFrame | relative=parent | 
    self.driver.switch_to.window(self.vars["root"])
    # 49 | selectFrame | index=1 | 
    self.driver.switch_to.frame(0)
    # 50 | echo | ponto11 | 
    self.driver.switch_to.default_content()
    # 51 | waitForElementVisible | id=selJustificativa | 30000
    self.driver.switch_to.frame(1)
    # 52 | click | id=selJustificativa | 
    print("ponto11")
    # 53 | echo | Ponto33 | 
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selJustificativa")))
    # 54 | select | id=selJustificativa | label=Justificativa de Arquivamento 01
    self.driver.find_element(By.ID, "selJustificativa").click()
    # 55 | echo | Ponto2 | 
    print("Ponto33")
    # 56 | click | id=selJustificativa | 
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Arquivamento 01']").click()
    # 57 | click | id=selCargoFuncao | 
    print("Ponto2")
    # 58 | select | id=selCargoFuncao | label=Assessor(a)
    self.driver.find_element(By.ID, "selJustificativa").click()
    # 59 | click | id=selCargoFuncao | 
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    # 60 | click | id=pwdSenha | 
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Assessor(a)']").click()
    # 61 | type | id=pwdSenha | arquivistaorg2
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    # 62 | click | id=sbmSalvar | 
    self.driver.find_element(By.ID, "pwdSenha").click()
    # 63 | pause | 5000 | 
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivistaorg2")
    # 64 | waitForElementVisible | xpath=//img[@alt='Desarquivar Processo'] | 30000
    self.driver.find_element(By.ID, "sbmSalvar").click()
    # 65 | click | xpath=//img[@alt='Desarquivar Processo'] | 
    time.sleep(5)
    # 66 | waitForElementVisible | id=selJustificativa | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Desarquivar Processo\']")))
    # 67 | select | id=selJustificativa | label=Justificativa de Desarquivamento 01
    self.driver.find_element(By.XPATH, "//img[@alt=\'Desarquivar Processo\']").click()
    # 68 | click | id=selJustificativa | 
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selJustificativa")))
    # 69 | click | css=body | 
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Desarquivamento 01']").click()
    # 70 | select | id=selCargoFuncao | label=Assessor(a)
    self.driver.find_element(By.ID, "selJustificativa").click()
    # 71 | click | id=selCargoFuncao | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 72 | click | id=pwdSenha | 
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Assessor(a)']").click()
    # 73 | type | id=pwdSenha | arquivistaorg2
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    # 74 | chooseOkOnNextConfirmation |  | 
    self.driver.find_element(By.ID, "pwdSenha").click()
    # 75 | click | id=sbmSalvar | 
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivistaorg2")
    # 77 | pause | 5000 | 
    self.driver.find_element(By.ID, "sbmSalvar").click()
    # 79 | selectFrame | index=0 | 
    time.sleep(5)
    # 80 | verifyElementPresent | xpath=//span[contains(.,'Termo de Arquivamento')] | 
    self.driver.switch_to.default_content()
    # 81 | verifyElementPresent | xpath=//span[contains(.,'Termo de Desarquivamento')] | 
    self.driver.switch_to.frame(0)
    elements = self.driver.find_elements(By.XPATH, "//span[contains(.,\'Termo de Arquivamento\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//span[contains(.,\'Termo de Desarquivamento\')]")
    assert len(elements) > 0
  
  def test_cadastrarProcessolegado(self):
    # Test name: CadastrarProcesso_legado
    # Step # | name | target | value
    # 1 | open | /sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8= | 
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI&infra_url=L3NlaS8=")
    # 2 | waitForElementVisible | id=txtUsuario | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "txtUsuario")))
    # 3 | click | id=txtUsuario | 
    self.driver.find_element(By.ID, "txtUsuario").click()
    # 4 | type | id=txtUsuario | arquivistaorg2
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivistaorg2")
    # 5 | waitForElementVisible | id=pwdSenha | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    # 6 | click | id=pwdSenha | 
    self.driver.find_element(By.ID, "pwdSenha").click()
    # 7 | type | id=pwdSenha | arquivistaorg2
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivistaorg2")
    # 8 | click | id=selOrgao | 
    self.driver.find_element(By.ID, "selOrgao").click()
    # 9 | select | id=selOrgao | label=Org2
    dropdown = self.driver.find_element(By.ID, "selOrgao")
    dropdown.find_element(By.XPATH, "//option[. = 'Org2']").click()
    # 10 | click | id=Acessar | 
    self.driver.find_element(By.ID, "Acessar").click()
    # 11 | waitForElementVisible | linkText=Iniciar Processo | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Iniciar Processo")))
    # 12 | click | linkText=Iniciar Processo | 
    self.driver.find_element(By.LINK_TEXT, "Iniciar Processo").click()
    # 13 | click | //*[@id="imgExibirTiposProcedimento"] | 
    self.driver.find_element(By.XPATH, "//*[@id=\"imgExibirTiposProcedimento\"]").click()
    # 14 | storeXpathCount | xpath=//a[contains(text(), 'Acesso à Informação: Demanda do e-SIC')] | error
    self.vars["error"] = len(self.driver.find_elements(By.XPATH, "//a[contains(text(), \'Acesso à Informação: Demanda do e-SIC\')]"))
    # 15 | if | ${error}==0 | 
    if self.driver.execute_script("return (arguments[0]==0)", self.vars["error"]):
      # 16 | click | //*[@id="imgExibirTiposProcedimento"] | 
      self.driver.find_element(By.XPATH, "//*[@id=\"imgExibirTiposProcedimento\"]").click()
      # 17 | end |  | 
    # 18 | click | linkText=Acesso à Informação: Demanda do e-SIC | 
    self.driver.find_element(By.LINK_TEXT, "Acesso à Informação: Demanda do e-SIC").click()
    # 19 | type | id=txtDescricao | teste arquivo
    self.driver.find_element(By.ID, "txtDescricao").send_keys("teste arquivo")
    # 20 | click | css=#divOptPublico .infraRadioLabel | 
    self.driver.find_element(By.CSS_SELECTOR, "#divOptPublico .infraRadioLabel").click()
    # 21 | click | css=#divInfraBarraComandosInferior > #btnSalvar > .infraTeclaAtalho | 
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraBarraComandosInferior > #btnSalvar > .infraTeclaAtalho").click()
    # 22 | selectFrame | index=1 | 
    self.driver.switch_to.frame(1)
    # 23 | waitForElementVisible | xpath=//img[@alt='Incluir Documento'] | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Incluir Documento\']")))
    # 24 | click | xpath=//img[@alt='Incluir Documento'] | 
    self.driver.find_element(By.XPATH, "//img[@alt=\'Incluir Documento\']").click()
    # 25 | waitForElementVisible | linkText=Despacho | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Despacho")))
    # 26 | click | linkText=Despacho | 
    self.driver.find_element(By.LINK_TEXT, "Despacho").click()
    # 27 | waitForElementVisible | css=#divOptPublico .infraRadioLabel | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#divOptPublico .infraRadioLabel")))
    # 28 | click | css=#divOptPublico .infraRadioLabel | 
    self.driver.find_element(By.CSS_SELECTOR, "#divOptPublico .infraRadioLabel").click()
    # 29 | click | id=btnSalvar | 
    self.vars["window_handles"] = self.driver.window_handles
    # 30 | storeWindowHandle | root | 
    self.driver.find_element(By.ID, "btnSalvar").click()
    # 31 | selectWindow | handle=${win3408} | 
    self.vars["win3408"] = self.wait_for_window(10000)
    # 32 | close |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 33 | selectWindow | handle=${root} | 
    self.driver.switch_to.window(self.vars["win3408"])
    # 34 | selectFrame | index=0 | 
    self.driver.close()
    # 35 | selectFrame | relative=parent | 
    self.driver.switch_to.window(self.vars["root"])
    # 36 | selectFrame | index=1 | 
    self.driver.switch_to.frame(0)
    # 37 | selectWindow | handle=${root} | 
    self.driver.switch_to.default_content()
    # 38 | selectFrame | index=0 | 
    self.driver.switch_to.frame(1)
    # 39 | selectFrame | relative=parent | 
    self.driver.switch_to.window(self.vars["root"])
    # 40 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 41 | click | xpath=//span | 
    self.driver.switch_to.default_content()
    # 42 | selectFrame | relative=parent | 
    self.driver.switch_to.frame(0)
    # 43 | selectFrame | index=1 | 
    self.driver.find_element(By.XPATH, "//span").click()
    # 44 | waitForElementVisible | xpath=//img[@alt='Concluir e Arquivar Processo'] | 30000
    self.driver.switch_to.default_content()
    # 45 | click | xpath=//img[@alt='Concluir e Arquivar Processo'] | 
    self.driver.switch_to.frame(1)
    # 46 | selectWindow | handle=${root} | 
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Concluir e Arquivar Processo\']")))
    # 47 | selectFrame | index=0 | 
    self.driver.find_element(By.XPATH, "//img[@alt=\'Concluir e Arquivar Processo\']").click()
    # 48 | selectFrame | relative=parent | 
    self.driver.switch_to.window(self.vars["root"])
    # 49 | selectFrame | index=1 | 
    self.driver.switch_to.frame(0)
    # 50 | echo | ponto11 | 
    self.driver.switch_to.default_content()
    # 51 | waitForElementVisible | id=selJustificativa | 30000
    self.driver.switch_to.frame(1)
    # 52 | click | id=selJustificativa | 
    print("ponto11")
    # 53 | echo | Ponto33 | 
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selJustificativa")))
    # 54 | select | id=selJustificativa | label=Justificativa de Arquivamento 01
    self.driver.find_element(By.ID, "selJustificativa").click()
    # 55 | //click | id=chkSinLegado | 
    print("Ponto33")
    # 56 | //click | id=txtDataArquivamento | 
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Arquivamento 01']").click()
    # 60 | click | id=selCargoFuncao | 
    print("Ponto2")
    # 61 | select | id=selCargoFuncao | label=Assessor(a)
    self.driver.find_element(By.ID, "selJustificativa").click()
    # 62 | click | id=selCargoFuncao | 
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    # 63 | click | id=pwdSenha | 
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Assessor(a)']").click()
    # 64 | type | id=pwdSenha | arquivistaorg2
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    # 65 | chooseOkOnNextConfirmation |  | 
    self.driver.find_element(By.ID, "pwdSenha").click()
    # 66 | click | css=#sbmSalvar > .infraTeclaAtalho | 
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivistaorg2")
    # 68 | //webdriverChooseOkOnVisibleConfirmation |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#sbmSalvar > .infraTeclaAtalho").click()
    elements = self.driver.find_elements(By.ID, "divInfraBarraLocalizacao")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//div[contains(.,\'Concluir e Arquivar Processo\')]")
    assert len(elements) > 0
  
