# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1100SEIGDAvaliacaoMassa():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["SELENIUMTEST_MODALIDADE"]):
      self.driver = webdriver.Chrome()
    else:
      self.driver = webdriver.Remote(command_executor=os.environ["SELENIUMTEST_SELENIUMHOST_URL"], desired_capabilities=DesiredCapabilities.CHROME)
    
    if ((not 'maximizar_screen' in os.environ) or os.environ['maximizar_screen'] == 'true'):
        self.driver.maximize_window()
    
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1110Verificafiltros(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.XPATH, "//span[text()='Avaliação de Processos']/../../../../a").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (91 registros - 1 a 50):"
    dropdown = self.driver.find_element(By.ID, "selUnidade")
    dropdown.find_element(By.XPATH, "//option[. = 'Arquivo01 - Arquivo01']").click()
    self.driver.find_element(By.ID, "selUnidade").click()
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (41 registros):"
    dropdown = self.driver.find_element(By.ID, "selUnidade")
    dropdown.find_element(By.XPATH, "//option[. = 'TESTE - Unidade de Teste 1']").click()
    self.driver.find_element(By.ID, "selUnidade").click()
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (50 registros):"
    dropdown = self.driver.find_element(By.ID, "selDestinacaoFinal")
    dropdown.find_element(By.XPATH, "//option[. = 'Eliminação']").click()
    self.driver.find_element(By.ID, "selDestinacaoFinal").click()
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (19 registros):"
    dropdown = self.driver.find_element(By.ID, "selDestinacaoFinal")
    dropdown.find_element(By.XPATH, "//option[. = 'Recolhimento']").click()
    self.driver.find_element(By.ID, "selDestinacaoFinal").click()
    dropdown = self.driver.find_element(By.ID, "selUnidade")
    dropdown.find_element(By.XPATH, "//option[. = 'Arquivo01 - Arquivo01']").click()
    self.driver.find_element(By.ID, "selUnidade").click()
    dropdown = self.driver.find_element(By.ID, "selDestinacaoFinal")
    dropdown.find_element(By.XPATH, "//option[. = 'Recolhimento']").click()
    self.driver.find_element(By.ID, "selDestinacaoFinal").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (26 registros):"
    dropdown = self.driver.find_element(By.ID, "selUnidade")
    dropdown.find_element(By.XPATH, "//option[. = 'TESTE - Unidade de Teste 1']").click()
    self.driver.find_element(By.ID, "selUnidade").click()
    dropdown = self.driver.find_element(By.ID, "selDestinacaoFinal")
    dropdown.find_element(By.XPATH, "//option[. = 'Eliminação']").click()
    self.driver.find_element(By.ID, "selDestinacaoFinal").click()
    self.driver.find_element(By.ID, "txtPeriodoDe").click()
    self.driver.find_element(By.ID, "txtPeriodoDe").send_keys("05/05/2000")
    self.driver.find_element(By.ID, "txtPeriodoA").click()
    self.driver.find_element(By.ID, "txtPeriodoA").send_keys("30/05/2010")
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraBarraComandosSuperior > #sbmPesquisar > .infraTeclaAtalho").click()
    self.driver.find_element(By.ID, "divInfraAreaTabela").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
  
  def test_1110Verificafiltroscont(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão Documental").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (91 registros - 1 a 50):"
    self.driver.find_element(By.ID, "txtPeriodoDe").click()
    self.driver.find_element(By.ID, "txtPeriodoDe").send_keys("05/05/2000")
    self.driver.find_element(By.ID, "txtPeriodoA").click()
    self.driver.find_element(By.ID, "txtPeriodoA").send_keys("30/05/2100")
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (91 registros - 1 a 50):"
    dropdown = self.driver.find_element(By.ID, "selAssunto")
    dropdown.find_element(By.XPATH, "//option[. = '012.3 - CAMPANHAS INSTITUCIONAIS. PUBLICIDADE (inclusive Cartazes, Folhetos, Anúncios, Folders e outros documentos de ca...']").click()
    self.driver.find_element(By.ID, "selAssunto").click()
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (57 registros - 1 a 50):"
  
  def test_1110VerificafiltrosRecolhimentoSemExpirarInterm(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão Documental").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    dropdown = self.driver.find_element(By.ID, "selAssunto")
    dropdown.find_element(By.XPATH, "//option[. = '012.3 - CAMPANHAS INSTITUCIONAIS. PUBLICIDADE (inclusive Cartazes, Folhetos, Anúncios, Folders e outros documentos de ca...']").click()
    self.driver.find_element(By.ID, "selAssunto").click()
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (57 registros - 1 a 50):"
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'99990.000001\')]/../../td[11]/a[2]")
    assert len(elements) == 0
  
  def test_1120EnviarEliminacao(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão Documental").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    dropdown = self.driver.find_element(By.ID, "selDestinacaoFinal")
    dropdown.find_element(By.XPATH, "//option[. = 'Eliminação']").click()
    self.driver.find_element(By.ID, "selDestinacaoFinal").click()
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (34 registros):"
    for i in range(0, 30):
      self.driver.find_element(By.ID, "divInfraAreaDados").click
      self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[10]/a[1]").click()
      #self.driver.find_element(By.ID, "sbmEliminacao").click()
      self.driver.switch_to.alert.accept()
      WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraBarraLocalizacao\"]")))
      assert self.driver.find_element(By.ID, "divInfraBarraLocalizacao").text == "Avaliação de Processos"
  
  def test_1130EnviarRecolhimento(self):
    self.driver.get(os.environ["SELENIUMTEST_SISTEMA_URL"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["SELENIUMTEST_SISTEMA_ORGAO"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("arquivista02")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("arquivista02")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão Documental").click()
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    dropdown = self.driver.find_element(By.ID, "selDestinacaoFinal")
    dropdown.find_element(By.XPATH, "//option[. = 'Recolhimento']").click()
    self.driver.find_element(By.ID, "selDestinacaoFinal").click()
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos para Avaliação (57 registros - 1 a 50):"
    for i in range(0, 25):
      self.driver.find_element(By.ID, "divInfraAreaDados").click()
      self.driver.find_element(By.XPATH, "//*[@id=\"divInfraAreaTabela\"]/table/tbody/tr[2]/td[10]/a[1]").click()
      #self.driver.find_element(By.ID, "sbmEliminacao").click()
      self.driver.switch_to.alert.accept()
      WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"divInfraBarraLocalizacao\"]")))
      assert self.driver.find_element(By.ID, "divInfraBarraLocalizacao").text == "Avaliação de Processos"
  
