# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test0206SEIGDArquivarFisicos():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_arquivar1a15(self):
    self.driver.get("http://sei.gd.nuvem.gov.br/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "lblUsuario").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selInfraUnidades")))
    dropdown = self.driver.find_element(By.ID, "selInfraUnidades")
    dropdown.find_element(By.XPATH, "//option[. = 'TESTE']").click()
    self.driver.find_element(By.ID, "selInfraUnidades").click()
    self.driver.find_element(By.LINK_TEXT, "Arquivamento").click()
    dropdown = self.driver.find_element(By.ID, "selTipoLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Tipo de Localizador 01']").click()
    time.sleep(5000)
    self.driver.find_element(By.ID, "selLocalizador").click()
    dropdown = self.driver.find_element(By.ID, "selLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'TLOC01-1']").click()
    self.driver.find_element(By.ID, "selTipoLocalizador").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "btnPesquisar").click()
    self.vars["win6058"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win6058"])
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "txtProtocolo")))
    self.driver.find_element(By.ID, "txtProtocolo").send_keys("99990.000015/2021-62,99990.000014/2021-18,99990.000013/2021-73,99990.000012/2021-29,99990.000011/2021-84,99990.000010/2021-30,99990.000009/2021-13,99990.000008/2021-61,99990.000007/2021-16,99990.000006/2021-71,99990.000005/2021-27,99990.000004/2021-82,99990.000003/2021-38,99990.000002/2021-93,99990.000001/2021-49")
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selTipoLocalizador")))
    dropdown = self.driver.find_element(By.ID, "selTipoLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Tipo de Localizador 01']").click()
    self.driver.find_element(By.ID, "selTipoLocalizador").click()
    time.sleep(3000)
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selLocalizador")))
    dropdown = self.driver.find_element(By.ID, "selLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'TLOC01-1']").click()
    self.driver.find_element(By.ID, "selLocalizador").click()
    self.driver.find_element(By.ID, "txtProtocolo").click()
    self.driver.find_element(By.ID, "txtProtocolo").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnArquivar").click()
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "sbmAtualizar")))
    self.driver.find_element(By.ID, "sbmAtualizar").click()
  
  def test_arquivar32a62(self):
    self.driver.get("http://sei.gd.nuvem.gov.br/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SEI&infra_url=L3NlaS8=")
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "lblUsuario").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selInfraUnidades")))
    dropdown = self.driver.find_element(By.ID, "selInfraUnidades")
    dropdown.find_element(By.XPATH, "//option[. = 'TESTE']").click()
    self.driver.find_element(By.ID, "selInfraUnidades").click()
    self.driver.find_element(By.LINK_TEXT, "Arquivamento").click()
    dropdown = self.driver.find_element(By.ID, "selTipoLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Tipo de Localizador 01']").click()
    time.sleep(5000)
    self.driver.find_element(By.ID, "selTipoLocalizador").click()
    dropdown = self.driver.find_element(By.ID, "selLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'TLOC01-1']").click()
    self.driver.find_element(By.ID, "selLocalizador").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "btnPesquisar").click()
    self.vars["win6058"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win6058"])
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "txtProtocolo")))
    self.driver.find_element(By.ID, "txtProtocolo").send_keys("99990.000062/2021-14,99990.000061/2021-61,99990.000060/2021-17,99990.000059/2021-92,99990.000058/2021-48,99990.000057/2021-01,99990.000056/2021-59,99990.000055/2021-12,99990.000054/2021-60,99990.000053/2021-15,99990.000052/2021-71,99990.000051/2021-26,99990.000050/2021-81,99990.000049/2021-57,99990.000048/2021-11,99990.000047/2021-68,99990.000046/2021-13,99990.000045/2021-79,99990.000044/2021-24,99990.000043/2021-80,99990.000042/2021-35,99990.000041/2021-91,99990.000040/2021-46,99990.000039/2021-11,99990.000038/2021-77,99990.000037/2021-22,99990.000036/2021-88,99990.000035/2021-33,99990.000034/2021-99,99990.000033/2021-44,99990.000032/2021-08")
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selTipoLocalizador")))
    dropdown = self.driver.find_element(By.ID, "selTipoLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'Tipo de Localizador 02']").click()
    self.driver.find_element(By.ID, "selTipoLocalizador").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "selLocalizador")))
    time.sleep(3000)
    dropdown = self.driver.find_element(By.ID, "selLocalizador")
    dropdown.find_element(By.XPATH, "//option[. = 'TLOC02-1']").click()
    self.driver.find_element(By.ID, "selLocalizador").click()
    self.driver.find_element(By.ID, "txtProtocolo").click()
    self.driver.find_element(By.ID, "txtProtocolo").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "btnArquivar").click()
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "sbmAtualizar")))
    self.driver.find_element(By.ID, "sbmAtualizar").click()
  
