# Generated by Selenium IDE
import os
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test0240SEIGDCadProcAcessoInfAut():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["local_do_teste"]):
        self.driver = webdriver.Chrome()
    else:
        self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)

    if ((not 'maximizar_screen' in os.environ) or os.environ['maximizar_screen'] == 'true'):
        self.driver.maximize_window()

    self.driver.implicitly_wait(10)    
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastrarProcessosFlood(self):
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "txtUsuario")))
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "pwdSenha")))
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "Acessar").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Iniciar Processo")))
    self.driver.find_element(By.CSS_SELECTOR, ".d-none #lnkInfraUnidade").click()
    self.driver.find_element(By.XPATH, "//td[contains(.,\'Unidade de Testes 1.2\')]").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".d-none #lnkInfraUnidade").click()
    self.driver.find_element(By.XPATH, "//td[contains(.,\'Unidade de Testes 1.1\')]").click()
    self.driver.find_element(By.LINK_TEXT, "Iniciar Processo").click()
    self.vars["error"] = len(self.driver.find_elements(By.XPATH, "//a[contains(text(),\'Acesso à Informação: Demanda do e-SIC\')]"))
    if self.driver.execute_script("return (arguments[0]==0)", self.vars["error"]):
      self.driver.find_element(By.ID, "imgExibirTiposProcedimento").click()
    self.driver.find_element(By.LINK_TEXT, "Acesso à Informação: Demanda do e-SIC").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtDescricao")))
    self.driver.find_element(By.ID, "txtDescricao").send_keys("teste arquivo")
    self.driver.find_element(By.ID, "lblPublico").click()
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraBarraComandosInferior > #btnSalvar > .infraTeclaAtalho").click()
    time.sleep(0.003)
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt=\'Incluir Documento\']")))
    self.driver.find_element(By.XPATH, "//img[@alt=\'Incluir Documento\']").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Externo")))
    self.driver.find_element(By.LINK_TEXT, "Externo").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "selSerie")))
    dropdown = self.driver.find_element(By.ID, "selSerie")
    dropdown.find_element(By.XPATH, "//option[. = 'Abaixo-Assinado']").click()
    time.sleep(0.001)
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtDataElaboracao")))
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "selSerie")))
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "txtDataElaboracao")))
    self.driver.find_element(By.ID, "txtDataElaboracao").click()
    self.driver.find_element(By.ID, "txtDataElaboracao").send_keys("01/01/2019")
    self.driver.find_element(By.ID, "lblDigitalizado").click()
    dropdown = self.driver.find_element(By.ID, "selTipoConferencia")
    dropdown.find_element(By.XPATH, "//option[. = 'Cópia Autenticada Administrativamente']").click()
    #self.driver.find_element(By.ID, "selTipoConferencia").click()
    self.driver.find_element(By.XPATH, "//div[@id='divSinArquivamento']/div/label").click()
    self.driver.find_element(By.ID, "lblPublico").click()
    self.driver.find_element(By.ID, "filArquivo").send_keys(os.getcwd()+"/seleniumIDE/02.45-SEI-GD-CadProcAcessoInf-Aut/exportedpython/teste.pdf")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraTd:nth-child(2)")))
    self.driver.find_element(By.CSS_SELECTOR, ".infraTd:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraTd:nth-child(2) > div").text == "teste.pdf"
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraBarraComandosInferior > #btnSalvar").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id='collapseControle']")))
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//img[@alt='Acompanhamento Especial']")))
    print("fim")
    print("fim2")
  
