# Generated by Selenium IDE
import pytest
import os
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1300ArquivamentoLegado():
  def setup_method(self, method):
    if ("LOCAL" == os.environ["local_do_teste"]):
      self.driver = webdriver.Chrome()
    else:
      self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    # self.driver.quit()
    self.vars = {}
  
  def test_01Legado(self):
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "Acessar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-none #lnkInfraUnidade").click()
    self.driver.find_element(By.XPATH, "//td[contains(.,\'Unidade de Testes 1.2\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-none #lnkInfraUnidade").click()
    self.driver.find_element(By.XPATH, "//td[contains(.,\'Unidade de Testes 1.1\')]").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    dropdown = self.driver.find_element(By.ID, "selTipoProcedimento")
    dropdown.find_element(By.XPATH, "//option[. = 'Acesso à Informação: Demanda do e-SIC']").click()
    self.driver.find_element(By.ID, "selTipoProcedimento").click()
    time.sleep(0.004)
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    time.sleep(0.004)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "imgInfraCheck")))
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.XPATH, "//label[@for=\'chkInfraItem0\']").click()
    self.driver.find_element(By.XPATH, "//label[@for=\'chkInfraItem1\']").click()
    self.driver.find_element(By.XPATH, "//label[@for=\'chkInfraItem2\']").click()
    self.driver.find_element(By.ID, "sbmArquivar").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selJustificativa")))
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Arquivamento 01']").click()
    self.driver.find_element(By.ID, "selJustificativa").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCheckboxLabel").click()
    self.vars["data"] = self.driver.execute_script("var d= new Date(); var m=((d.getMonth()+1)<10)?\'0\'+(d.getMonth()+1):(d.getMonth()+1); var di=(d.getDate()<10)?\'0\'+(d.getDate()):(d.getDate());  return di+\'/\'+m+\'/\'+(d.getFullYear());")
    self.driver.find_element(By.ID, "txtDataArquivamento").click()
    self.driver.find_element(By.ID, "txtDataArquivamento").send_keys(self.vars["data"])
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Agente Fiscalizador de Contrato']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmSalvar").click()
    WebDriverWait(self.driver, 60).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Pendências de Arquivamento (5 registros):"
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selTipoProcedimento")))
    dropdown = self.driver.find_element(By.ID, "selTipoProcedimento")
    dropdown.find_element(By.XPATH, "//option[. = 'Comunicação: Evento Institucional Público Externo']").click()
    self.driver.find_element(By.ID, "selTipoProcedimento").click()
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "imgInfraCheck")))
    self.driver.find_element(By.ID, "imgInfraCheck").click()
    self.driver.find_element(By.ID, "sbmArquivar").click()
    dropdown = self.driver.find_element(By.ID, "selJustificativa")
    dropdown.find_element(By.XPATH, "//option[. = 'Justificativa de Arquivamento 01']").click()
    self.driver.find_element(By.ID, "selJustificativa").click()
    self.driver.find_element(By.ID, "chkSinLegado").click()
    self.driver.find_element(By.ID, "txtDataArquivamento").click()
    self.driver.find_element(By.ID, "txtDataArquivamento").send_keys(self.vars["data"])
    dropdown = self.driver.find_element(By.ID, "selCargoFuncao")
    dropdown.find_element(By.XPATH, "//option[. = 'Ordenador de Despesa, Substituto(a)']").click()
    self.driver.find_element(By.ID, "selCargoFuncao").click()
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmSalvar").click()
    WebDriverWait(self.driver, 60).until(expected_conditions.visibility_of_element_located((By.ID, "sbmPesquisar")))
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Arquivo da Unidade")))
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    time.sleep(0.004)
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    time.sleep(0.004)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selTipoProcedimento")))
    dropdown = self.driver.find_element(By.ID, "selTipoProcedimento")
    dropdown.find_element(By.XPATH, "//option[. = 'Todos']").click()
    self.driver.find_element(By.ID, "selTipoProcedimento").click()
    time.sleep(0.004)
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    time.sleep(0.004)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos Arquivados (48 registros):"
  
  def test_02Legado(self):
    self.driver.get(os.environ["base_url"]+"/sip/login.php?sigla_orgao_sistema="+os.environ["selOrgao"]+"&sigla_sistema=SEI")
    self.driver.find_element(By.ID, "divUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "Acessar").click()
    dropdown = self.driver.find_element(By.ID, "selInfraUnidades")
    dropdown.find_element(By.XPATH, "//option[. = 'TESTE_1_1']").click()
    self.driver.find_element(By.ID, "selInfraUnidades").click()
    self.driver.find_element(By.LINK_TEXT, "Pendências de Arquivamento").click()
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Pendências de Arquivamento (5 registros):"
    self.driver.find_element(By.LINK_TEXT, "Arquivo da Unidade").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selTipoProcedimento")))
    dropdown = self.driver.find_element(By.ID, "selTipoProcedimento")
    dropdown.find_element(By.XPATH, "//option[. = 'Comunicação: Evento Institucional Público Externo']").click()
    self.driver.find_element(By.ID, "selTipoProcedimento").click()
    time.sleep(0.004)
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    time.sleep(0.004)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos Arquivados (48 registros):"
    self.driver.find_element(By.XPATH, "//div[@id=\'divInfraAreaTabela\']/table/tbody/tr[2]/td[8]").click()
    elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'1 ano, 9 meses\')]")
    assert len(elements) > 0
    dropdown = self.driver.find_element(By.ID, "selTipoProcedimento")
    dropdown.find_element(By.XPATH, "//option[. = 'Acesso à Informação: Demanda do e-SIC']").click()
    self.driver.find_element(By.ID, "selTipoProcedimento").click()
    time.sleep(0.004)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#sbmPesquisar > .infraTeclaAtalho")))
    self.driver.find_element(By.CSS_SELECTOR, "#sbmPesquisar > .infraTeclaAtalho").click()
    time.sleep(0.004)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#divInfraAreaTabela > label")))
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
    dropdown = self.driver.find_element(By.ID, "selInfraUnidades")
    dropdown.find_element(By.XPATH, "//option[. = 'ArquivoGeral02']").click()
    self.driver.find_element(By.ID, "selInfraUnidades").click()
    time.sleep(0.004)
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[10]/a").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Avaliação de Processos")))
    self.driver.find_element(By.LINK_TEXT, "Avaliação de Processos").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "selTipoProcedimento")))
    dropdown = self.driver.find_element(By.ID, "selTipoProcedimento")
    dropdown.find_element(By.XPATH, "//option[. = 'Todos']").click()
    self.driver.find_element(By.ID, "selTipoProcedimento").click()
    time.sleep(0.004)
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    time.sleep(0.004)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".infraCaption")))
    self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".infraCaption").text == "Lista de Processos Arquivados (47 registros):"
    dropdown = self.driver.find_element(By.ID, "selTipoProcedimento")
    dropdown.find_element(By.XPATH, "//option[. = 'Comunicação: Evento Institucional Público Externo']").click()
    time.sleep(0.004)
    self.driver.find_element(By.ID, "sbmPesquisar").click()
    time.sleep(0.004)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#divInfraAreaTabela > label")))
    self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#divInfraAreaTabela > label").text == "Nenhum registro encontrado."
  
